using Inventory.Models.Abstractions;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Inventory.Models.Domain
{
    public class Product: BaseEntity
    {
        [Required]
        [StringLength(100)]
        public string ProductName { get; set; }

        [Required]
        [StringLength(6)]
        public string ProductCode { get; set; } // Autogenerated

        [StringLength(100)]
        public string? Description { get; set; }

        [Required]
        public int Stock { get; set; }

        [Required]
        [Column(TypeName = "smallmoney")]
        public decimal Price { get; set; }

        public int CategoryId { get; set; } // Navigation Property
        public Category Category { get; set; } // Object reference

        private bool _isAvailable;

        public bool IsAvailable 
        {
            get { return _isAvailable; }

            set
            {
                if (Stock > 0) _isAvailable = true;

                _isAvailable = false;
            }
        }
    }
}
